version: "3.1"

services:
  ui:
    image: react-docker
    container_name: frontend
    build: ./minesweeper
    volumes:
      - ./minesweeper:/app
    ports:
      - "3000:3000"
    networks:
      - app_network

networks:
  app_network:
    driver: bridge